// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnIQL7rFSdaZ9GvKEIg6-unArDXfyRDPs',
    appId: '1:927540652804:web:6b7356f8887f5b81607e51',
    messagingSenderId: '927540652804',
    projectId: 'sample-task-app-bmzs0q',
    authDomain: 'sample-task-app-bmzs0q.firebaseapp.com',
    storageBucket: 'sample-task-app-bmzs0q.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmSF8Sv6TCdC4nvg1-S-AQ5SWwZa9vGLY',
    appId: '1:927540652804:android:4002b1b0b8e8e418607e51',
    messagingSenderId: '927540652804',
    projectId: 'sample-task-app-bmzs0q',
    storageBucket: 'sample-task-app-bmzs0q.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-AYPpoyBiXKOflqVyqvUZW0NPElrluk',
    appId: '1:927540652804:ios:0ba322615da411f7607e51',
    messagingSenderId: '927540652804',
    projectId: 'sample-task-app-bmzs0q',
    storageBucket: 'sample-task-app-bmzs0q.appspot.com',
    iosBundleId: 'com.jobhunter.jobBoard',
  );
}
